# Generated by Django 5.2.10 on 2026-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foundperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found'), ('UNDER_REVIEW', 'Under Review')], default='MISSING', max_length=20),
        ),
    ]
