# Generated by Django 5.2.10 on 2026-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_missingperson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='status',
        ),
    ]
