# Generated by Django 5.2.10 on 2026-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_policestation_alter_foundperson_matched_missing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found')], default='MISSING', max_length=10),
        ),
    ]
